<?
class Utility{
		
	public function __construct()
	{
	}

	static public function judete($id = 0)
	{
		$judete = array(
			'0' => '--Alege judet--',
			'1'  => 'Bucuresti',
			'2'  => 'Alba',
			'3'  => 'Arad',
			'4'  => 'Arges',
			'5'  => 'Bacau',
			'6'  => 'Bihor',
			'7'  => 'Bistrita-Nasaud',
			'8'  => 'Botosani',
			'9'  => 'Brasov',
			'10' => 'Braila',
			'11' => 'Buzau',
			'12' => 'Caras-Severin',
			'13' => 'Calarasi',
			'14' => 'Cluj',
			'15' => 'Constanta',
			'16' => 'Covasna',
			'17' => 'Dambovita',
			'18' => 'Dolj',
			'19' => 'Galati',
			'20' => 'Giurgiu',
			'21' => 'Gorj',
			'22' => 'Harghita',
			'23' => 'Hunedoara',
			'24' => 'Ialomita',
			'25' => 'Iasi',
			'26' => 'Ilfov',
			'27' => 'Maramures',
			'28' => 'Mehedinti',
			'29' => 'Mures',
			'30' => 'Neamt',
			'31' => 'Olt',
			'32' => 'Prahova',
			'33' => 'Satu Mare',
			'34' => 'Salaj',
			'35' => 'Sibiu',
			'36' => 'Suceava',
			'37' => 'Teleorman',
			'38' => 'Timis',
			'39' => 'Tulcea',
			'40' => 'Vaslui',
			'41' => 'Valcea',
			'42' => 'Vrancea'
		);
		krsort($judete);
		return ($id==0) ? $judete : $judete[$id];
	}

	static public function orase( $id_judet = 0, $id_oras = 0 )
	{
		$orase = array
		(	
			'2' => array(
				'1' => 'Alba Iulia',
				'2' => 'Blaj',
				'3' => 'Sebes',
				'4' => 'Abrud',
				'5' => 'Baia de aries',
				'6' => 'Campeni',
				'7' => 'Cugir',
				'8' => 'Ocna Mures',
				'9' => 'Teius',
				'10' => 'Zlatna',
				'11' =>	'Aiud'
			),
			'3' => array(
				'1' => 'Arad',
				'2' => 'Curtici',
				'3' => 'Ineu',
				'4' => 'Lipova',
				'5' => 'Nadlac',
				'6' => 'Pancota',
				'7' => 'Pecica',
				'8' => 'Santana',
				'9' => 'Sebis',
				'10' => 'Chisineu-Cris',
			),
			'42' => array(
				'1' => 'Focsani',
				'2' => 'Adjud',
				'3' => 'Marasesti',
				'4' => 'Odobesti',
				'5' => 'Panciu',
			),
			'40' => array(
				'1' => 'Vaslui',
				'2' => 'Barlad',
				'3' => 'Husi',
				'4' => 'Murgeni',
				'5' => 'Negresti',
			),
			'41' => array(
				'1' => 'Ramnicu Valcea',
				'2' => 'Dragasani',
				'3' => 'Calimanesti',
				'4' => 'Brezoi',
				'5' => 'Horezu',
				'6' => 'Baile Olanesti',
				'7' => 'Ocnele Mari',
				'8' => 'Baile Govora',
				'9' => 'Babeni',
				'10' => 'Balcesti',
				'11' => 'Berbesti',
				),
			'39' => array(
				'1' => 'Tulcea',
				'2' => 'Macin',
				'3' => 'Badadag',
				'4' => 'Isaccea',
				'5' => 'Sulina',
				),
			'38' => array(
				'1' => 'Timisoara',
				'2' => 'Lugoj',
				'3' => 'Sannicolau',
				'4' => 'Mare',
				'5' => 'Jimbolia',
				'6' => 'Buzias',
				'7' => 'Faget',
				'8' => 'Deta',
				'9' => 'Gataia',
				'10' => 'Recas',
				'11' => 'Ciacova',
				),
			'37' => array(
				'1' => 'Alexandria',
				'2' => 'Rosiorii de Vede',
				'3' => 'Turnu',
				'4' => 'Magurele',
				'5' => 'Zimnicea',
				'6' => 'Videle',	
			),
			'36' => array(
				'1' => 'Suceava',
				'2' => 'Falticeni',
				'3' => 'Radauti',
				'4' => 'Campulung Moldovenesc',
				'5' => 'Vatra Dornei',
				'6' => 'Gura Humorului',
				'7' => 'Siret',
				'8' => 'Solca',
				'9' => 'Brosteni',
				'10' => 'Cajvana',
				'11' => 'Dolhasca',
				'12' => 'Frasin',
				'13' => 'Liteni',
				'14' => 'Milisauti',
				'15' => 'Salcea',
				'16' => 'Vicovu de Sus',
				),
			'35' => array(
				'1' => 'Sibiu',
				'2' => 'Medias',
				'3' => 'Avrig',
				'4' => 'Agnita',
				'5' => 'Cisnadie',
				'6' => 'Dumbraveni',
				'7' => 'Ocna Sibiului',
				'8' => 'Miercurea Sibiului',
				'9' => 'Saliste',
				'10' => 'Talmaciu',
				'11' => 'CopsaMica',

				),
			'33' => array(
					'1' => 'Satu Mare',
					'2' => 'Carei',
					'3' => 'Negresti-Oas',
					'4' => 'Tasnad',
					'5' => 'Livada',
					'6' => 'Ardud',

					),
			'34' => array(
				'1' => 'Zalau',
				'2' => 'Simleu Silvaniei',
				'3' => 'Jibou',
				'4' => 'Cehu Silvaniei',
						),
			'32' => array(
					'1' => 'Ploiesti',
					'2' => 'Campina',
					'3' => 'Azuga',
					'4' => 'Baicoi',
					'5' => 'Boldesti-Scaeni',
					'6' => 'Breaza',
					'7' => 'Busteni',
					'8' => 'Comarnic',
					'9' => 'Mizil',
					'10' => 'Plopeni',
					'11' => 'Sinaia',
					'12' => 'Slanic',
					'13' => 'Urlati',
					'14' => 'Valenii de Munte',

						),
			'31' => array(
				'1' => 'Slatina',
				'2' => 'Caracal',
				'3' => 'Bals',
				'4' => 'Corabia',
				'5' => 'Dunare',
				'6' => 'Scornicesti',
				'7' => 'Draganesti-Olt',
				'8' => 'Piatra-Olt',
				'9' => 'Potcoava',
						),
			'30' => array(
				'1' => 'Piatra-Neamt',
				'2' => 'Roman',
				'3' => 'Targu-Neamt',
				'4' => 'Bicaz',
				'5' => 'Roznov',
				),
			'29' => array(
				'1' => 'Targu Mures',
				'2' => 'Reghin',
				'3' => 'Sighisoara',
				'4' => 'Tarnaveni',
				'5' => 'Ludus',
				'6' => 'Sarmasu',
				'7' => 'Sovata',
				'8' => 'Iernut',
				'9' => 'Ungheni',
				'10' => 'Miercurea Mirajului',
				'11' => 'Sangiorgiu-de-Padure',
				),
			'28' => array(
				'1' => 'Drobeta-Turnu Severin',
				'2' => 'Orsova',
				'3' => 'Sterhaia',
				'4' => 'Vanju Mare',
				'5' => 'Baia de Arama',
				),
			'27' => array(
				'1' => 'Baia Mare',
				'2' => 'Sighetu Marmatiei',
				'3' => 'Borsa',
				'4' => 'Baia-Sprie',
				'5' => 'Viseu de Sus',
				'6' => 'Targu Lapus',
				'7' => 'Sein',
				'8' => 'Socuta Mare',
				'9' => 'Ulmeni',
				'10' => 'Tauti Magheraus',
				'11' => 'Cavnic',
				'12' => 'Salistea de Sus',
				'13' => 'Dragomiresti',
				),
			'1' => array(
				'1' => 'Bucuresti - Sector 1',
				'2' => 'Bucuresti - Sector 2',
				'3' => 'Bucuresti - Sector 3',
				'4' => 'Bucuresti - Sector 4',
				'5' => 'Bucuresti - Sector 5',
				'6' => 'Bucuresti - Sector 6',
				),
			'25' => array(
				'1' => 'Iasi',
				'2' => 'Pascani',
				'3' => 'Harlau',
				'4' => 'TarguFrumos',
				'5' => 'PoduIloaiei',
				),
			'24' => array(
				'1' => 'Slobozia',
				'2' => 'Fetesti',
				'3' => 'Urziceni',
				'4' => 'Tandarei',
				'5' => 'Amara',
				'6' => 'Cazanesti',
				),
			'23' => array(
				'1' => 'Petrosani',
				'2' => 'Deva',
				'3' => 'Hunedoara',
				'4' => 'Vulcan',
				'5' => 'Lupeni',
				'6' => 'Petrila',
				'7' => 'Orastie',
				'8' => 'Brad',
				'9' => 'Simeria',
				'10' => 'Calan',
				'11' => 'Uricani',
				'12' => 'Hateg',
				'13' => 'Gioagiu',
				'14' => 'Aninoasa',
				),
			'22' => array(
				'1' => 'Miercurea-Ciuc',
				'2' => 'Odorheiul Secuiesc',
				'3' => 'Ghiorgheni',
				'4' => 'Toplita',
				'5' => 'Cristuru',
				'6' => 'Secuiesc',
				'7' => 'Vlahita',
				'8' => 'Balan',
				'9' => 'Borsec',
				'10' => 'Baile Tusnad',
				),
			'21' => array(
				'1' => 'Targu-Jiu',
				'2' => 'Motru',
				'3' => 'Rovinari',
				'4' => 'Matasari',
				'5' => 'Bumbesti-Jiu',
				'6' => 'Targu Carbunesti',
				'7' => 'Turceni',
				'8' => 'Tismana',
				'9' => 'Novaci',
				'10' => 'Ticleni',
				),
			'20' => array(
				'1' => 'Giurgiu',
				'2' => 'Bolintin-Vale',
				'3' => 'Mihailesti',
				),
			'19' => array(
				'1' => 'Galati',
				'2' => 'Tecuci',
				'3' => 'Targu Bujor',
				'4' => 'Beresti',
				),
			'18' => array(
				'1' => 'Craiova',
				'2' => 'Bailesti',
				'3' => 'Calafat',
				'4' => 'Filias',
				'5' => 'Dabuleni',
				'6' => 'Segarcea',
				'7' => 'Bechet',
				),
			'17' => array(
				'1' => 'Targoviste',
				'2' => 'Moreni',
				'3' => 'Pucioasa',
				'4' => 'Gaiesti',
				'5' => 'Titu',
				'6' => 'Fieni',
				'7' => 'Racari',
				),
			'16' => array(
				'1' => 'Sfantu Gheorghe',
				'2' => 'Targu Secuiesc',
				'3' => 'Covasna',
				'4' => 'Baraolt',
				'5' => 'Intorsura Buzaului',
				),
			'15' => array(
				'1' => 'Constanta',
				'2' => 'Medgidia',
				'3' => 'Mangalia',
				'4' => 'Navodari',
				'5' => 'Cernavoda',
				'6' => 'Ovidiu',
				'7' => 'Harsova',
				'8' => 'Murfatlar',
				'9' => 'Eforie',
				'10' => 'Techirghiol',
				'11' => 'Baneasa',
				'12' => 'Negru Voda',
				),
			'14' => array(
				'1' => 'Cluj-Napoca',
				'2' => 'Turda',
				'3' => 'Dej',
				'4' => 'Campia Turzii',
				'5' => 'Gherla',
				'6' => 'Huedin',
				),
			'12' => array(
				'1' => 'Resita',
				'2' => 'Caransebes',
				'3' => 'Otelu Rosu',
				'4' => 'Anina',
				'5' => 'Baile Herculane',
				'6' => 'Bocsa',
				'7' => 'Moldova Noua',
				'8' => 'Oravita',
				),
			'13' => array(
				'1' => 'Calarasi',
				'2' => 'Oltenita',
				'3' => 'Budesti',
				'4' => 'Fundulea',
				'5' => 'Lehliu-Gara',
				),
			'5' => array(
				'1' => 'Bacau',
				'2' => 'Onesti',
				'3' => 'Buhusi',
				'4' => 'Moinesti',
				'5' => 'Comanesti',
				'6' => 'Darmanesti',
				'7' => 'Targu Ocna',
				'8' => 'Slanic Moldova',
				),
			'9' => array(
				'1' => 'Brasov',
				'2' => 'Fagaras',
				'3' => 'Sacele',
				'4' => 'Zarnesti',
				'5' => 'Rasnov',
				'6' => 'Codlea',
				'7' => 'Victoria',
				'8' => 'Rupea',
				'9' => 'Predeal',
				'10' => 'Ghimbav',
				),
			'10' => array(
				'1' => 'Braila',
				'2' => 'Ianca',
				'3' => 'Insuratiei',
				'4' => 'Faureni',
				),
			'8' => array(
				'1' => 'Botosani',
				'2' => 'Dorohoi',
				'3' => 'Darabani',
				'4' => 'Flamanzi',
				'5' => 'Saveni',
				'6' => 'Bucecea',
				'7' => 'Stefanesti',
				),
			'7' => array(
				'1' => 'Bistrita',
				'2' => 'Nasaud',
				'3' => 'Beclean',
				'4' => 'Stangiors-Bai',
				),
			'6' => array(
				'1' => 'Oradea',
				'2' => 'Salonta',
				'3' => 'Marghita',
				'4' => 'Sacueni',
				'5' => 'Beius',
				'6' => 'Alesd',
				'7' => 'Stei',
				'8' => 'Vascau',
				'9' => 'Nucet',
				),
			'11' => array(
				'1' => 'Buzau',
				'2' => 'Ramnicu Sarat',
				'3' => 'Nehoiu',
				'4' => 'Patarlagele',
				'5' => 'Pogoanele',
				),
			'4' => array(
				'1' => 'Pitesti',
				'2' => 'Mioveni',
				'3' => 'Campulung',
				'4' => 'Curtea de Arges',
				'5' => 'Stefanesti',
				'6' => 'Costesti',
				'7' => 'Topoloveni',
				),
			'26' => array(
				'1' => 'Bragadiru',
				'2' => 'Buftea',
				'3' => 'Chitila',
				'4' => 'Magurele',
				'5' => 'Otopeni',
				'6' => 'Pantelimon',
				'7' => 'Popesti-Leordeni',
				'8' => 'Voluntari',
				),

		);

		if($id_judet)
		{
			return ($id_oras == 0) ? $orase[$id_judet] : $orase[$id_judet][$id_oras];
		}
	}



};



?>